USE defaultdb;

CREATE TABLE novels(
idNovel INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(50) NOT NULL,
author VARCHAR(50) NOT NULL,
year INT NOT NULL,
gender VARCHAR(50) NOT NULL
);

CREATE TABLE authors(
idAuthor INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
name VARCHAR(50) NOT NULL, 
lastname VARCHAR(50) NOT NULL, 
country VARCHAR(50) NOT NULL
);

CREATE TABLE users(
idUser INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
user VARCHAR(50) NOT NULL,
pasword VARCHAR(50) NOT NULL,
name VARCHAR(50) NOT NULL, 
email VARCHAR(50) NOT NULL
);
